#!/bin/bash 
if [ $# -eq 0 ]; then
  echo "No email address supplied"
  exit 1
fi
export PUBLIC_IP_PRIMARY="$(dig TXT +short o-o.myaddr.l.google.com @ns1.google.com | awk -F'"' '{ print $2}')"
export PUBLIC_IP_SECONDARY="$(dig +short myip.opendns.com @resolver1.opendns.com)"
#echo ${PUBLIC_IP_PRIMARY}
#echo ${PUBLIC_IP_SECONDARY}
printf "Interface: ${IFACE}\nIP Address: ${PUBLIC_IP_PRIMARY}\n(Alternative source: ${PUBLIC_IP_SECONDARY})\n" | mail -s "[CCS] IP Address" $1

exit 0
